### PR TITLE
2006 Conference content links

### PR DESCRIPTION
**Pull request by kaitlinnewson**
Related to #3. Should cover all of 2006, except for the carpooling link that appears on https://code4lib.org/conference/2006/. This page appears to be missing.

### CODE REVIEW

**Comment by wickr** [comment]
I almost got these changes uploaded, but the links didn't work. I think the permalinks need an ending slash, making the page generate to `linkname/index.html` so links like `conference/2006/linkname` will work on the server. The Jekyll server routes them fine though, locally they're ok. I hit this earlier with the conference links: https://github.com/code4lib/code4lib.org/commit/13eeadba0933b31a7a79cb975e900124a3550cbe
I'll try again tomorrow to get these changes live.

**Comment by kaitlinnewson** [comment]
Thanks @wickr. Let me know what works and I'll try to get through some of the other years as well.

**Comment by wickr** [comment]
@kaitlinnewson yeah that fixed it, I pushed a commit here: https://github.com/code4lib/code4lib.org/commit/8e651f5f0c03d4eb64408103489ad951d39d7c1d
That's all live on the server now. Thanks for working on this.

**Comment by wickr** [comment]
@kaitlinnewson you should have write access to this repo now, if that helps you push directly here for PRs

**Pull request merged**
